version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      xunit:
        patterns:
          - "xunit*"
  - package-ecosystem: "npm"
    directory: "src/projektanker.code-butler"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
